# Generated by Django 3.2.16 on 2024-09-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D3S1358_1', models.FloatField(blank=True, null=True)),
                ('D3S1358_2', models.FloatField(blank=True, null=True)),
                ('ТН01_1', models.FloatField(blank=True, null=True)),
                ('ТН01_2', models.FloatField(blank=True, null=True)),
                ('D12S391_1', models.FloatField(blank=True, null=True)),
                ('D12S391_2', models.FloatField(blank=True, null=True)),
                ('D1S1656_1', models.FloatField(blank=True, null=True)),
                ('D1S1656_2', models.FloatField(blank=True, null=True)),
                ('D10S1248_1', models.FloatField(blank=True, null=True)),
                ('D10S1248_2', models.FloatField(blank=True, null=True)),
                ('D22S1045_1', models.FloatField(blank=True, null=True)),
                ('D22S1045_2', models.FloatField(blank=True, null=True)),
                ('D2S441_1', models.FloatField(blank=True, null=True)),
                ('D2S441_2', models.FloatField(blank=True, null=True)),
                ('D7S820_1', models.FloatField(blank=True, null=True)),
                ('D7S820_2', models.FloatField(blank=True, null=True)),
                ('D13S317_1', models.FloatField(blank=True, null=True)),
                ('D13S317_2', models.FloatField(blank=True, null=True)),
                ('FGA_1', models.FloatField(blank=True, null=True)),
                ('FGA_2', models.FloatField(blank=True, null=True)),
                ('TPO X_1', models.FloatField(blank=True, null=True)),
                ('TPO X_2', models.FloatField(blank=True, null=True)),
                ('D18S51_1', models.FloatField(blank=True, null=True)),
                ('D18S51_2', models.FloatField(blank=True, null=True)),
                ('D16S539_1', models.FloatField(blank=True, null=True)),
                ('D16S539_2', models.FloatField(blank=True, null=True)),
                ('D8S1179_1', models.FloatField(blank=True, null=True)),
                ('D8S1179_2', models.FloatField(blank=True, null=True)),
                ('CSF  1PO_1', models.FloatField(blank=True, null=True)),
                ('CSF  1PO_2', models.FloatField(blank=True, null=True)),
                ('D5S818_1', models.FloatField(blank=True, null=True)),
                ('D5S818_2', models.FloatField(blank=True, null=True)),
                ('vWA_1', models.FloatField(blank=True, null=True)),
                ('vWA_2', models.FloatField(blank=True, null=True)),
                ('D21S11_1', models.FloatField(blank=True, null=True)),
                ('D21S11_2', models.FloatField(blank=True, null=True)),
                ('SE33_1', models.FloatField(blank=True, null=True)),
                ('SE33_2', models.FloatField(blank=True, null=True)),
                ('D2S1338_1', models.FloatField(blank=True, null=True)),
                ('D2S1338_2', models.FloatField(blank=True, null=True)),
                ('D19S433_1', models.FloatField(blank=True, null=True)),
                ('D19S433_2', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
